version: "3.8"

services:
  app:
    container_name: broadcast-api
    image: broadcast-api
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 3000:3000