apiVersion: v1
kind: ConfigMap
metadata:
  name: broadcast-api-config
data:
  config.yaml: |
    server:
      port: 3000
      timeout: 30s

    database:
      URL: ${DB_URL}
      host: ${DB_HOST}
      port: ${DB_PORT}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      name: ${DB_NAME}

    jwt:
      secret: ${JWT_SECRET}
      expirationTime: 24h

    smtp:
      host: ${SMTP_HOST}
      port: ${SMTP_PORT}
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
      fromName: "Broadcast API"
      fromAddr: ${SMTP_FROM_ADDR}

    queue:
      workerCount: 5
      maxRetries: 3
      retryBackoff: 5m
      rateLimit: 10
