apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DB_HOST: {{ .Values.secrets.dbHost | quote }}
  DB_PORT: {{ .Values.secrets.dbPort | quote }}
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_NAME: {{ .Values.secrets.dbName | quote }}
  DB_URL: {{ .Values.secrets.dbUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  SMTP_HOST: {{ .Values.secrets.smtpHost | quote }}
  SMTP_PORT: {{ .Values.secrets.smtpPort | quote }}
  SMTP_USERNAME: {{ .Values.secrets.smtpUsername | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  SMTP_FROM_ADDR: {{ .Values.secrets.smtpFromAddr | quote }}